-- 1. Profiles table to extend auth.users
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  full_name text,
  username text unique,
  avatar_url text,
  role text default 'user' check (role in ('user', 'admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Destinations table
create table destinations (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  location text not null,
  price decimal(10, 2) not null,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Bookings table
create table bookings (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  destination_id bigint references destinations(id) on delete cascade not null,
  check_in date not null,
  check_out date not null,
  num_travelers integer not null default 1,
  total_price decimal(10, 2) not null,
  status text default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (OPTIONAL: Disabling for simple demo start)
-- alter table profiles enable row level security;
-- alter table destinations enable row level security;
-- alter table bookings enable row level security;

-- Create a trigger to automatically create a profile when a user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'user');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Seed some initial data
insert into destinations (title, description, location, price, image_url)
values 
('Paris Getaway', 'Experience the romance of Paris with this 5-day tour of the Eiffel Tower, Louvre, and more.', 'Paris, France', 1200.00, 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34'),
('Bali Paradise', 'Relax on the beautiful beaches of Bali and explore vibrant jungles and temples.', 'Bali, Indonesia', 850.00, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4'),
('Swiss Alps Adventure', 'A thrilling week of skiing and hiking in the heart of the Swiss Alps.', 'Zermatt, Switzerland', 1500.00, 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b');
